/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author COMPUTER
 */
public class FrmZodiac extends javax.swing.JFrame {

    /**
     * Creates new form FrmZodiac
     */
    public FrmZodiac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBulan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtZodiac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDeskripsi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Date"));

        jLabel1.setText("Tanggal");

        jLabel2.setText("Bulan");

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Deskripsi"));

        jLabel3.setText("Zodiac");

        txaDeskripsi.setColumns(20);
        txaDeskripsi.setRows(5);
        jScrollPane1.setViewportView(txaDeskripsi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZodiac))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZodiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(txtTanggal.getText());
        int y = Integer.parseInt(txtBulan.getText());
        if (x >= 21 && y == 3 || y == 4 && x <= 20) {
            if (y == 3 || y == 4) {
                String zodiak = "Aries (" + x + " Mar - " + y + " Apr)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: suka menonjolkan diri, senang beraktifitas, menyukai kepemimpinan.");    
            }
        } else if (x >= 21 && y == 4 || y == 5 && x <= 20) {
            if (y == 4 || y == 5) {
                String zodiak = "Taurus (" + x + " Apr - " + y + " Mei)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: suka hak milik dan tanah.");
            }
        } else if (x >= 21 && y == 5 || y == 6 && x <= 20) {
            if (y == 5 || y == 6) {
                String zodiak = "Gamini (" + x + " Mei - " + y + " Jun)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: menjadi penjual jasa");
            }
        } else if (x >= 21 && y == 6 || y == 7 && x <= 22) {
            if (y == 6 || y == 7) {
                String zodiak = "Cancer (" + x + " Jun - " + y + " Jul)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: sangat peduli urusan rumah");
            }
        } else if (x >= 23 && y == 7 || y == 8 && x <= 22) {
            if (y == 7 || y == 8) {
                String zodiak = "Leo (" + x + " Jul - " + y + " Aug)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: suka hak milik dan tanah.");
            }
        } else if (x >= 23 && y == 8 || y == 9 && x <= 22) {
            if (y == 8 || y == 9) {
                String zodiak = "Virgo (" + x + " Aug - " + y + " Sep)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: bekerja cepat dan tepat, sehat dan higienis, suka menganalisa yang lain.");
            }
        } else if (x >= 23 && y == 9 || y == 10 && x <= 22) {
            if (y == 9 || y == 10) {
                String zodiak = "Libra (" + x + " Sep - " + y + " Okt)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: menyenangi ide estetika, dalam seni dan lingkungan kerja yang berorientasi kemasyarakatan, adil pada siapa saja");
            }
        } else if (x >= 23 && y == 10 || y == 11 && x <= 22) {
            if (y == 10 || y == 11) {
                String zodiak = "Scorpio (" + x + " Okt - " + y + " Nov)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: penuh misteri atau rahasia, menyukai problema dan riset.");
            }
        } else if (x >= 23 && y == 11 || y == 12 && x <= 21) {
            if (y == 11 || y == 12) {
                String zodiak = "Sagitarius (" + x + " Nov - " + y + " Des)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: pengembara, mengejar filsafat, menyukai penelitian.");
            }
        } else if (x >= 22 && y == 12 || y == 1 && x <= 19) {
            if (y == 12 || y == 1) {
                String zodiak = "Capricorn (" + x + " Des - " + y + " Jan)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: mengejar keuntungan bisnis (fiansial) dan status social.");
            }
        } else if (x >= 20 && y == 1 || y == 2 && x <= 19) {
            if (y == 1 || y == 2) {
                String zodiak = "Aquarius (" + x + " Jan - " + y + " Feb)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: mengejar segi kemanusiaan dan pengetahuan, menyukai aktifitas kelompok.");
            }
        } else if (x >= 20 && y == 2 || y == 3 && x <= 20) {
            if (y == 2 || y == 3) {
                String zodiak = "Pisces (" + x + " Feb - " + y + " Mar)";
                txtZodiac.setText(zodiak);
                txaDeskripsi.setText("Sifat Umum: menyukai hal-hal spiritual, kesenian dan lautan.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmZodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmZodiac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDeskripsi;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtZodiac;
    // End of variables declaration//GEN-END:variables
}
